import type { DecodedCall, DecodedRevert } from "./decode/types";
import type { SimulateOutcome, SimulateRequest } from "./simulate";

export interface ReportInput {
  chainName: string;
  chainId: number;
  request: SimulateRequest;
  outcome: SimulateOutcome;
  decodedCall?: DecodedCall | null;
  decodedRevert?: DecodedRevert | null;
  shareUrl?: string;
}

function fmt(value: unknown): string {
  if (typeof value === "bigint") return value.toString();
  if (Array.isArray(value)) return value.map(fmt).join(", ");
  if (value !== null && typeof value === "object") {
    return JSON.stringify(value, (_, v: unknown) =>
      typeof v === "bigint" ? v.toString() : v,
    );
  }
  return String(value);
}

const STATUS_LABEL: Record<SimulateOutcome["status"], string> = {
  success: "Success ✅",
  revert: "Reverted ❌",
  error: "RPC error ⚠️",
};

/** Portable markdown summary of a simulation (PLAN §8 report export). */
export function toMarkdownReport(input: ReportInput): string {
  const { request, outcome } = input;
  const lines: string[] = [];

  lines.push("# EVM Transaction Troubleshooter report", "");
  lines.push(`**Chain:** ${input.chainName} (${input.chainId})`, "");

  lines.push("## Request", "");
  if (request.from) lines.push(`- **From:** \`${request.from}\``);
  lines.push(`- **To:** \`${request.to}\``);
  if (request.value !== undefined)
    lines.push(`- **Value:** ${request.value.toString()} wei`);
  if (request.blockNumber !== undefined)
    lines.push(`- **Block:** ${request.blockNumber.toString()}`);
  if (request.data) lines.push(`- **Calldata:** \`${request.data}\``);
  if (request.stateOverride?.length)
    lines.push(`- **State overrides:** ${request.stateOverride.length}`);
  lines.push("");

  if (input.decodedCall?.functionName) {
    lines.push("## Decoded call", "");
    lines.push(
      `\`${input.decodedCall.signature ?? input.decodedCall.functionName}\` (${input.decodedCall.source})`,
      "",
    );
    if (input.decodedCall.args?.length) {
      lines.push("| Arg | Type | Value |", "| --- | --- | --- |");
      for (const arg of input.decodedCall.args) {
        lines.push(
          `| ${arg.name ?? ""} | \`${arg.type}\` | \`${fmt(arg.value)}\` |`,
        );
      }
      lines.push("");
    }
  }

  lines.push("## Result", "");
  lines.push(`**${STATUS_LABEL[outcome.status]}**`, "");
  if (outcome.status === "success") {
    lines.push(`- **Return data:** \`${outcome.returnData}\``);
  } else if (outcome.status === "revert") {
    lines.push(`- **Message:** ${outcome.message}`);
    lines.push(`- **Revert data:** \`${outcome.revertData}\``);
    if (input.decodedRevert) {
      lines.push(`- **Decoded:** ${input.decodedRevert.message}`);
    }
  } else {
    lines.push(`- **Error:** ${outcome.message}`);
  }
  lines.push("");

  if (input.shareUrl) {
    lines.push("## Reproduce", "");
    lines.push(`[Open this simulation](${input.shareUrl})`, "");
  }

  lines.push("---", "");
  lines.push(
    "_Generated by [EVM Transaction Troubleshooter](https://github.com/UnchainedSoulBT/evm-troubleshooter)._",
  );

  return lines.join("\n");
}
